version: 2

jobs:
  build:
    working_directory: /go/src/github.com/tendermint/go-crypto
    docker:
    - image: circleci/golang:1.10.0
      environment:
        GOBIN: /tmp/workspace/bin
    steps:
      - run: mkdir -p /tmp/workspace/bin
      - run: mkdir -p /tmp/workspace/profiles
      - checkout
      - restore_cache:
              keys:
              - v1-dep-{{ .Branch }}
      - run:
              name: test
              command: |
                go version
                cd $PROJECT_PATH && make get_tools && make all
    - save_cache:
        key: v1-dep-{{ .Branch }}
        paths:
        - /go/pkg
